specfile_path: initial-setup.spec
upstream_package_name: initial-setup
upstream_tag_template: r{version}-1
srpm_build_deps:
  - make
actions:
  create-archive:
    - "make BUILD_ARGS=sdist archive"
    - 'bash -c "cp dist/*.tar.gz ."'
    - 'bash -c "ls -1 initial-setup-*.tar.gz"'
jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-rawhide

  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-eln

  - job: copr_build
    trigger: commit
    metadata:
      targets:
        - fedora-rawhide
        - fedora-eln
      branch: master
      owner: "@rhinstaller"
      project: Anaconda
      preserve_project: True

  - job: copr_build
    trigger: commit
    metadata:
      targets:
        - fedora-latest
      branch: master
      owner: "@rhinstaller"
      project: Anaconda-devel
      preserve_project: True
